### ISSUE TITLE
Two serial Vallox devices cannot be operated at the same time.

### ISSUE THREAD

**Issue by Sprocket02** [gitMiguel/openhab2-addons#5]
I want to connect two Vallox SE (80SE & 90SE) devices with the binding. Every single device works, but not both at the same time. I get the following error message in Openhab (version 2.5.1):

```
2020-03-04 12:18:45.305 [DEBUG] [lox.internal.handler.ValloxSEHandler] - Connection failed

java.io.IOException: Port in use

	at org.openhab.binding.vallox.internal.connection.ValloxSerialConnector.connect(ValloxSerialConnector.java:92) ~[?:?]

	at org.openhab.binding.vallox.internal.handler.ValloxSEHandler.connect(ValloxSEHandler.java:115) ~[?:?]

	at org.openhab.binding.vallox.internal.handler.ValloxSEHandler.lambda$0(ValloxSEHandler.java:379) ~[?:?]

	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_222]

	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_222]

	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_222]

	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_222]

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_222]

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_222]

	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]

Caused by: org.eclipse.smarthome.io.transport.serial.PortInUseException

	at org.eclipse.smarthome.io.transport.serial.internal.SerialPortIdentifierImpl.open(SerialPortIdentifierImpl.java:61) ~[?:?]

	at org.openhab.binding.vallox.internal.connection.ValloxSerialConnector.connect(ValloxSerialConnector.java:68) ~[?:?]

	... 9 more

==> /var/log/openhab2/events.log <==

2020-03-04 12:18:45.321 [hingStatusInfoChangedEvent] - 'vallox:se-serial:upstairs' changed from UNKNOWN to OFFLINE (COMMUNICATION_ERROR): Port in use

```

Here my Things cobfiguration:

```
Thing vallox:se-serial:upstairs "Lüftung oben" [ serialPort="/dev/ttyUSB0", panelNumber=5 ]

Thing vallox:se-serial:downstairs "Lüftung unten" [ serialPort="/dev/ttyUSB1", panelNumber=5 ]
```

**Comment by Sprocket02** [comment]
I get the following error message in Openhab (version 2.5.1) when I changed for example the fanspeed:

```
2020-03-05 18:55:22.079 [ome.event.ItemCommandEvent] - Item 'FanSpeed2' received command 4

2020-03-05 18:55:22.117 [nt.ItemStatePredictedEvent] - FanSpeed2 predicted to become 4

2020-03-05 18:55:22.142 [vent.ItemStateChangedEvent] - FanSpeed2 changed from 3 to 4

==> /var/log/openhab2/openhab.log <==

2020-03-05 18:55:22.151 [DEBUG] [ernal.connection.ValloxBaseConnector] - Wrote 01-26-11-29-0F-70

2020-03-05 18:55:22.151 [DEBUG] [ernal.connection.ValloxBaseConnector] - Send queue handler started

2020-03-05 18:55:22.654 [DEBUG] [ernal.connection.ValloxBaseConnector] - Wrote 01-26-11-29-0F-70

2020-03-05 18:55:23.156 [DEBUG] [ernal.connection.ValloxBaseConnector] - Wrote 01-26-11-29-0F-70

2020-03-05 18:55:23.660 [DEBUG] [ernal.connection.ValloxBaseConnector] - Wrote 01-26-11-29-0F-70

2020-03-05 18:55:24.162 [DEBUG] [ernal.connection.ValloxBaseConnector] - Wrote 01-26-11-29-0F-70

2020-03-05 18:55:24.665 [DEBUG] [lox.internal.handler.ValloxSEHandler] - Reconnecting after error: Ack byte not received for telegram: 01-26-11-29-0F-70

==> /var/log/openhab2/events.log <==

2020-03-05 18:55:24.668 [hingStatusInfoChangedEvent] - 'vallox:se-serial:downstairs' changed from ONLINE to OFFLINE (COMMUNICATION_ERROR): Ack byte not received for telegram: 01-26-11-29-0F-70

==> /var/log/openhab2/openhab.log <==

2020-03-05 18:55:25.156 [TRACE] [lox.internal.handler.ValloxSEHandler] - Telegram received OK 01-11-21-71-00-A4

2020-03-05 18:55:25.158 [DEBUG] [ng.vallox.internal.telegram.Telegram] - Channels parsed from telegram {status#firePlaceBoosterOn=OFF, setting#activateFirePlaceBooster=OFF, status#remoteControlOn=OFF}

2020-03-05 18:55:25.162 [TRACE] [lox.internal.handler.ValloxSEHandler] - Telegram not for us 01-21-11-00-A3-D6

2020-03-05 18:55:25.290 [TRACE] [lox.internal.handler.ValloxSEHandler] - Telegram received OK 01-11-21-A3-01-D7

2020-03-05 18:55:25.292 [DEBUG] [ng.vallox.internal.telegram.Telegram] - Channels parsed from telegram {status#postHeatingIndicator=OFF, setting#humidityAdjustState=OFF, setting#co2AdjustState=OFF, setting#powerState=ON, setting#postHeatingState=OFF, maintenance#filterGuardIndicator=OFF, alarm#faultIndicator=OFF, maintenance#serviceReminderIndicator=OFF}

2020-03-05 18:55:25.303 [TRACE] [lox.internal.handler.ValloxSEHandler] - Telegram not for us 01-21-11-00-29-5C

2020-03-05 18:55:25.306 [TRACE] [lox.internal.handler.ValloxSEHandler] - Telegram received OK 01-11-21-29-0F-6B

2020-03-05 18:55:25.309 [DEBUG] [ng.vallox.internal.telegram.Telegram] - Channels parsed from telegram {fanControl#fanSpeed=4}

2020-03-05 18:55:25.313 [TRACE] [lox.internal.handler.ValloxSEHandler] - Telegram not for us 01-21-11-00-35-68

2020-03-05 18:55:25.317 [TRACE] [lox.internal.handler.ValloxSEHandler] - Telegram received OK 01-11-21-35-96-FE

2020-03-05 18:55:25.320 [DEBUG] [ng.vallox.internal.telegram.Telegram] - Channels parsed from telegram {efficiency#averageEfficiency=77, efficiency#inEfficiency=77, efficiency#outEfficiency=77, temperature#tempIncoming=16}

2020-03-05 18:55:25.324 [TRACE] [lox.internal.handler.ValloxSEHandler] - Telegram not for us 01-21-11-00-A3-D6

2020-03-05 18:55:25.328 [TRACE] [lox.internal.handler.ValloxSEHandler] - Telegram received OK 01-11-21-A3-01-D7

2020-03-05 18:55:25.331 [DEBUG] [ng.vallox.internal.telegram.Telegram] - Channels parsed from telegram {status#postHeatingIndicator=OFF, setting#humidityAdjustState=OFF, setting#co2AdjustState=OFF, setting#powerState=ON, setting#postHeatingState=OFF, maintenance#filterGuardIndicator=OFF, alarm#faultIndicator=OFF, maintenance#serviceReminderIndicator=OFF}

2020-03-05 18:55:25.340 [TRACE] [lox.internal.handler.ValloxSEHandler] - Telegram not for us 01-21-11-00-71-A4

==> /var/log/openhab2/events.log <==

2020-03-05 18:55:26.155 [vent.ItemStateChangedEvent] - Grohe_Leistung changed from 75 to 73

==> /var/log/openhab2/openhab.log <==

2020-03-05 18:55:27.238 [TRACE] [lox.internal.handler.ValloxSEHandler] - Telegram received OK 01-11-21-71-00-A4

2020-03-05 18:55:27.239 [DEBUG] [ng.vallox.internal.telegram.Telegram] - Channels parsed from telegram {status#firePlaceBoosterOn=OFF, setting#activateFirePlaceBooster=OFF, status#remoteControlOn=OFF}

2020-03-05 18:55:27.363 [TRACE] [lox.internal.handler.ValloxSEHandler] - Telegram received OK 01-11-20-2B-00-5D

2020-03-05 18:55:27.365 [DEBUG] [ng.vallox.internal.telegram.Telegram] - Channels parsed from telegram {status#co2=0}

2020-03-05 18:55:27.490 [TRACE] [lox.internal.handler.ValloxSEHandler] - Telegram received OK 01-11-20-2C-00-5E

2020-03-05 18:55:27.492 [DEBUG] [ng.vallox.internal.telegram.Telegram] - Channels parsed from telegram {status#co2=0}

2020-03-05 18:55:27.626 [TRACE] [lox.internal.handler.ValloxSEHandler] - Telegram received OK 01-11-20-35-96-FD

2020-03-05 18:55:27.631 [DEBUG] [ng.vallox.internal.telegram.Telegram] - Channels parsed from telegram {efficiency#averageEfficiency=77, efficiency#inEfficiency=77, efficiency#outEfficiency=77, temperature#tempIncoming=16}

2020-03-05 18:55:27.760 [TRACE] [lox.internal.handler.ValloxSEHandler] - Telegram received OK 01-11-20-34-9A-00

2020-03-05 18:55:27.765 [DEBUG] [ng.vallox.internal.telegram.Telegram] - Channels parsed from telegram {efficiency#averageEfficiency=77, efficiency#inEfficiency=77, efficiency#outEfficiency=77, temperature#tempInside=18}

2020-03-05 18:55:27.895 [TRACE] [lox.internal.handler.ValloxSEHandler] - Telegram received OK 01-11-20-32-81-E5

2020-03-05 18:55:27.900 [DEBUG] [ng.vallox.internal.telegram.Telegram] - Channels parsed from telegram {temperature#tempOutside=9, efficiency#averageEfficiency=77, efficiency#inEfficiency=77, efficiency#outEfficiency=77}

2020-03-05 18:55:27.910 [TRACE] [lox.internal.handler.ValloxSEHandler] - Telegram received OK 01-11-20-33-87-EC

2020-03-05 18:55:27.915 [DEBUG] [ng.vallox.internal.telegram.Telegram] - Channels parsed from telegram {efficiency#averageEfficiency=77, temperature#tempExhaust=11, efficiency#inEfficiency=77, efficiency#outEfficiency=77}

2020-03-05 18:55:28.218 [DEBUG] [lox.internal.handler.ValloxSEHandler] - Closing connection

2020-03-05 18:55:28.230 [DEBUG] [ernal.connection.ValloxBaseConnector] - Listener removed: org.openhab.binding.vallox.internal.handler.ValloxSEHandler@1c61aa7

2020-03-05 18:55:28.232 [DEBUG] [ernal.connection.ValloxBaseConnector] - Send queue handler stopped

2020-03-05 18:55:28.253 [DEBUG] [nal.connection.ValloxSerialConnector] - Serial connection closed

2020-03-05 18:55:28.256 [DEBUG] [ernal.connection.ValloxBaseConnector] - Listener registered: org.openhab.binding.vallox.internal.handler.ValloxSEHandler@1c61aa7

2020-03-05 18:55:28.258 [DEBUG] [nal.connection.ValloxSerialConnector] - Connecting to /dev/ttyUSB1

2020-03-05 18:55:28.269 [DEBUG] [nal.connection.ValloxSerialConnector] - Connected to /dev/ttyUSB1

==> /var/log/openhab2/events.log <==

2020-03-05 18:55:28.274 [hingStatusInfoChangedEvent] - 'vallox:se-serial:downstairs' changed from OFFLINE (COMMUNICATION_ERROR): Ack byte not received for telegram: 01-26-11-29-0F-70 to ONLINE

==> /var/log/openhab2/openhab.log <==

2020-03-05 18:55:28.574 [TRACE] [lox.internal.handler.ValloxSEHandler] - Connection already open

==> /var/log/openhab2/events.log <==

2020-03-05 18:55:29.743 [vent.ItemStateChangedEvent] - Current_DateTime changed from 2020-03-05T18:54:29.731+0100 to 2020-03-05T18:55:29.734+0100

==> /var/log/openhab2/openhab.log <==

2020-03-05 18:55:30.315 [TRACE] [lox.internal.handler.ValloxSEHandler] - Telegram received OK 01-11-20-2A-2A-86

2020-03-05 18:55:30.319 [DEBUG] [ng.vallox.internal.telegram.Telegram] - Channels parsed from telegram {status#humidity=-4.411764705882353}

2020-03-05 18:55:30.327 [TRACE] [lox.internal.handler.ValloxSEHandler] - Telegram not for us 01-21-11-00-A3-D6

2020-03-05 18:55:30.461 [TRACE] [lox.internal.handler.ValloxSEHandler] - Telegram received OK 01-11-21-A3-01-D7

2020-03-05 18:55:30.464 [DEBUG] [ng.vallox.internal.telegram.Telegram] - Channels parsed from telegram {status#postHeatingIndicator=OFF, setting#humidityAdjustState=OFF, setting#co2AdjustState=OFF, setting#powerState=ON, setting#postHeatingState=OFF, maintenance#filterGuardIndicator=OFF, alarm#faultIndicator=OFF, maintenance#serviceReminderIndicator=OFF}

2020-03-05 18:55:30.471 [TRACE] [lox.internal.handler.ValloxSEHandler] - Telegram not for us 01-21-11-00-29-5C

2020-03-05 18:55:30.473 [TRACE] [lox.internal.handler.ValloxSEHandler] - Telegram received OK 01-11-21-29-0F-6B

2020-03-05 18:55:30.480 [DEBUG] [ng.vallox.internal.telegram.Telegram] - Channels parsed from telegram {fanControl#fanSpeed=4}

2020-03-05 18:55:30.485 [TRACE] [lox.internal.handler.ValloxSEHandler] - Telegram not for us 01-21-11-00-35-68

2020-03-05 18:55:30.487 [TRACE] [lox.internal.handler.ValloxSEHandler] - Telegram received OK 01-11-21-35-96-FE

2020-03-05 18:55:30.490 [DEBUG] [ng.vallox.internal.telegram.Telegram] - Channels parsed from telegram {efficiency#averageEfficiency=77, efficiency#inEfficiency=77, efficiency#outEfficiency=77, temperature#tempIncoming=16}

2020-03-05 18:55:30.494 [TRACE] [lox.internal.handler.ValloxSEHandler] - Telegram not for us 01-21-11-00-A3-D6

2020-03-05 18:55:30.497 [TRACE] [lox.internal.handler.ValloxSEHandler] - Telegram received OK 01-11-21-A3-01-D7

2020-03-05 18:55:30.500 [DEBUG] [ng.vallox.internal.telegram.Telegram] - Channels parsed from telegram {status#postHeatingIndicator=OFF, setting#humidityAdjustState=OFF, setting#co2AdjustState=OFF, setting#powerState=ON, setting#postHeatingState=OFF, maintenance#filterGuardIndicator=OFF, alarm#faultIndicator=OFF, maintenance#serviceReminderIndicator=OFF}

2020-03-05 18:55:30.507 [TRACE] [lox.internal.handler.ValloxSEHandler] - Telegram not for us 01-21-11-00-71-A4

2020-03-05 18:55:35.475 [TRACE] [lox.internal.handler.ValloxSEHandler] - Telegram received OK 01-11-21-71-00-A4

2020-03-05 18:55:35.479 [DEBUG] [ng.vallox.internal.telegram.Telegram] - Channels parsed from telegram {status#firePlaceBoosterOn=OFF, setting#activateFirePlaceBooster=OFF, status#remoteControlOn=OFF}

2020-03-05 18:55:35.482 [TRACE] [lox.internal.handler.ValloxSEHandler] - Telegram not for us 01-21-11-00-A3-D6

2020-03-05 18:55:35.610 [TRACE] [lox.internal.handler.ValloxSEHandler] - Telegram received OK 01-11-21-A3-01-D7

2020-03-05 18:55:35.612 [DEBUG] [ng.vallox.internal.telegram.Telegram] - Channels parsed from telegram {status#postHeatingIndicator=OFF, setting#humidityAdjustState=OFF, setting#co2AdjustState=OFF, setting#powerState=ON, setting#postHeatingState=OFF, maintenance#filterGuardIndicator=OFF, alarm#faultIndicator=OFF, maintenance#serviceReminderIndicator=OFF}

2020-03-05 18:55:35.620 [TRACE] [lox.internal.handler.ValloxSEHandler] - Telegram not for us 01-21-11-00-29-5C

2020-03-05 18:55:35.623 [TRACE] [lox.internal.handler.ValloxSEHandler] - Telegram received OK 01-11-21-29-0F-6B

2020-03-05 18:55:35.625 [DEBUG] [ng.vallox.internal.telegram.Telegram] - Channels parsed from telegram {fanControl#fanSpeed=4}

2020-03-05 18:55:35.629 [TRACE] [lox.internal.handler.ValloxSEHandler] - Telegram not for us 01-21-11-00-35-68

2020-03-05 18:55:35.632 [TRACE] [lox.internal.handler.ValloxSEHandler] - Telegram received OK 01-11-21-35-96-FE

2020-03-05 18:55:35.634 [DEBUG] [ng.vallox.internal.telegram.Telegram] - Channels parsed from telegram {efficiency#averageEfficiency=77, efficiency#inEfficiency=77, efficiency#outEfficiency=77, temperature#tempIncoming=16}

2020-03-05 18:55:35.641 [TRACE] [lox.internal.handler.ValloxSEHandler] - Telegram not for us 01-21-11-00-A3-D6

2020-03-05 18:55:35.643 [TRACE] [lox.internal.handler.ValloxSEHandler] - Telegram received OK 01-11-21-A3-01-D7

2020-03-05 18:55:35.646 [DEBUG] [ng.vallox.internal.telegram.Telegram] - Channels parsed from telegram {status#postHeatingIndicator=OFF, setting#humidityAdjustState=OFF, setting#co2AdjustState=OFF, setting#powerState=ON, setting#postHeatingState=OFF, maintenance#filterGuardIndicator=OFF, alarm#faultIndicator=OFF, maintenance#serviceReminderIndicator=OFF}

2020-03-05 18:55:35.659 [TRACE] [lox.internal.handler.ValloxSEHandler] - Telegram not for us 01-21-11-00-71-A4
```

When I remove one of the systems from the configuration, then I can change the fanspeed without any error messages.

**Comment by Sprocket02** [comment]
Hi, I tried to configure serial2net with the following steps:

`apt-get install ser2net`

`sudo nano /etc/ser2net.conf` add line

`4000:raw:0:/dev/ttyUSB1:9600 8DATABITS NONE 1STOPBIT`

`sudo /etc/init.d/ser2net restart`

After that I changed the Thing configuration to the following:

`Thing vallox:se-tcp:downstairs "Lüftung unten" [ tcpHost="127.0.0.1", tcpPort=4000, panelNumber=5 ]`

With that configuration I got the following error message:

```
2020-03-06 09:40:03.811 [DEBUG] [ernal.connection.ValloxBaseConnector] - Listener registered: org.openhab.binding.vallox.internal.handler.ValloxSEHandler@1383ede

2020-03-06 09:40:03.821 [DEBUG] [nternal.connection.ValloxIpConnector] - Connected to 127.0.0.1:4000

2020-03-06 09:40:03.825 [DEBUG] [nternal.connection.ValloxIpConnector] - Data listener started

2020-03-06 09:40:03.831 [hingStatusInfoChangedEvent] - 'vallox:se-tcp:downstairs' changed from OFFLINE (COMMUNICATION_ERROR): Connection refused (Connection refused) to ONLINE
```

**Comment by gitMiguel** [comment]
That's not an error message. Or do you mean that nothing happens after that?

**Comment by Sprocket02** [comment]
No, I can't set or read any value. There are no further logs from the binding.

**Comment by gitMiguel** [comment]
Please try to setup the binding with PaperUI just to minimize configuration problems. Restart could also help at this point when multiple changes are made.

**Comment by Sprocket02** [comment]
Ok, one step further. Only one system is connected via tcp. No system via serial. But when I what to change a Value I get the following messages:

```
2020-03-06 15:03:08.511 [DEBUG] [lox.internal.handler.ValloxSEHandler] - Initializing Vallox SE handler
2020-03-06 15:03:08.514 [DEBUG] [nternal.connection.ValloxIpConnector] - Tcp Connection initialized
2020-03-06 15:03:08.517 [DEBUG] [ernal.connection.ValloxBaseConnector] - Listener registered: org.openhab.binding.vallox.internal.handler.ValloxSEHandler@bfd33e
2020-03-06 15:03:08.520 [DEBUG] [nternal.connection.ValloxIpConnector] - Connected to 127.0.0.1:4000
2020-03-06 15:03:08.526 [DEBUG] [ernal.connection.ValloxBaseConnector] - Wrote 01-25-11-00-33-6A
2020-03-06 15:03:08.527 [hingStatusInfoChangedEvent] - 'vallox:se-tcp:downstairs' changed from INITIALIZING to UNKNOWN
2020-03-06 15:03:08.526 [DEBUG] [ernal.connection.ValloxBaseConnector] - Send queue handler started
2020-03-06 15:03:08.524 [DEBUG] [nternal.connection.ValloxIpConnector] - Data listener started
2020-03-06 15:03:08.536 [hingStatusInfoChangedEvent] - 'vallox:se-tcp:downstairs' changed from UNKNOWN to ONLINE
2020-03-06 15:03:09.028 [DEBUG] [ernal.connection.ValloxBaseConnector] - Wrote 01-25-11-00-35-6C
2020-03-06 15:03:09.530 [DEBUG] [ernal.connection.ValloxBaseConnector] - Wrote 01-25-11-00-A3-DA
2020-03-06 15:03:10.032 [DEBUG] [ernal.connection.ValloxBaseConnector] - Wrote 01-25-11-00-AF-E6
2020-03-06 15:03:10.534 [DEBUG] [ernal.connection.ValloxBaseConnector] - Wrote 01-25-11-00-A3-DA
2020-03-06 15:03:11.036 [DEBUG] [ernal.connection.ValloxBaseConnector] - Wrote 01-25-11-00-AB-E2
2020-03-06 15:03:11.538 [DEBUG] [ernal.connection.ValloxBaseConnector] - Wrote 01-25-11-00-A6-DD
2020-03-06 15:03:12.040 [DEBUG] [ernal.connection.ValloxBaseConnector] - Wrote 01-25-11-00-A3-DA
2020-03-06 15:03:12.542 [DEBUG] [ernal.connection.ValloxBaseConnector] - Wrote 01-25-11-00-32-69
2020-03-06 15:03:18.523 [TRACE] [lox.internal.handler.ValloxSEHandler] - Connection already open
2020-03-06 15:03:28.526 [TRACE] [lox.internal.handler.ValloxSEHandler] - Connection already open
2020-03-06 15:03:32.281 [ome.event.ItemCommandEvent] - Item 'FanSpeed2' received command 4
2020-03-06 15:03:32.285 [nt.ItemStatePredictedEvent] - FanSpeed2 predicted to become 4
2020-03-06 15:03:32.345 [vent.ItemStateChangedEvent] - FanSpeed2 changed from 5 to 4
2020-03-06 15:03:32.549 [DEBUG] [ernal.connection.ValloxBaseConnector] - Wrote 01-25-11-29-0F-6F
2020-03-06 15:03:33.051 [DEBUG] [ernal.connection.ValloxBaseConnector] - Wrote 01-25-11-29-0F-6F
2020-03-06 15:03:33.553 [DEBUG] [ernal.connection.ValloxBaseConnector] - Wrote 01-25-11-29-0F-6F
2020-03-06 15:03:34.055 [DEBUG] [ernal.connection.ValloxBaseConnector] - Wrote 01-25-11-29-0F-6F
2020-03-06 15:03:34.556 [DEBUG] [ernal.connection.ValloxBaseConnector] - Wrote 01-25-11-29-0F-6F
2020-03-06 15:03:35.058 [DEBUG] [lox.internal.handler.ValloxSEHandler] - Reconnecting after error: Ack byte not received for telegram: 01-25-11-29-0F-6F
2020-03-06 15:03:35.063 [hingStatusInfoChangedEvent] - 'vallox:se-tcp:downstairs' changed from ONLINE to OFFLINE (COMMUNICATION_ERROR): Ack byte not received for telegram: 01-25-11-29-0F-6F
2020-03-06 15:03:38.529 [DEBUG] [lox.internal.handler.ValloxSEHandler] - Closing connection
2020-03-06 15:03:38.535 [DEBUG] [ernal.connection.ValloxBaseConnector] - Listener removed: org.openhab.binding.vallox.internal.handler.ValloxSEHandler@bfd33e
2020-03-06 15:03:38.537 [DEBUG] [ernal.connection.ValloxBaseConnector] - Send queue handler stopped
2020-03-06 15:03:38.540 [DEBUG] [nternal.connection.ValloxIpConnector] - Interrupt message listener
2020-03-06 15:03:38.545 [DEBUG] [nternal.connection.ValloxIpConnector] - Telegram listener stopped
2020-03-06 15:03:38.549 [DEBUG] [nternal.connection.ValloxIpConnector] - Closed
2020-03-06 15:03:38.551 [DEBUG] [ernal.connection.ValloxBaseConnector] - Listener registered: org.openhab.binding.vallox.internal.handler.ValloxSEHandler@bfd33e
2020-03-06 15:03:38.554 [DEBUG] [nternal.connection.ValloxIpConnector] - Connected to 127.0.0.1:4000
2020-03-06 15:03:38.559 [DEBUG] [nternal.connection.ValloxIpConnector] - Data listener started
2020-03-06 15:03:38.559 [hingStatusInfoChangedEvent] - 'vallox:se-tcp:downstairs' changed from OFFLINE (COMMUNICATION_ERROR): Ack byte not received for telegram: 01-25-11-29-0F-6F to ONLINE
```

**Comment by gitMiguel** [comment]
Ok so the connection is properly opened to the tcp port but nothing "comes through". This has something to do with "serial side" or ser2net configuration.

First try tcp connection with your upstairs unit to see if it behaves differently. Also please revise your setup to tee that nothing else reserves the serial device.

**Comment by Sprocket02** [comment]
Meanwhile, I also think that my second adapter is not OK. Will investigate further.

**Comment by Sprocket02** [comment]
Got a new adapter. This configured via serial2net and it works. Now I have both systems running, one via serial connection and the other via tcp.

**Comment by gitMiguel** [comment]
Nice! So the problem was a faulty adapter. For completeness sake, can you test your setup by connecting them both directly using serial as you initially had it configured when you filed this issue?

**Comment by gitMiguel** [comment]
@Sprocket02 did you see my latest question/request?

**Comment by Sprocket02** [comment]
Basically, it also runs with two serial adapters. Sometimes I get a message that a port is blocked. A restart of the plugin or OpenHAB then helps.

**Comment by Sprocket02** [comment]
Here the error message regarding the port issue:

```
2020-04-28 13:47:49.118 [DEBUG] [al.se.connection.ValloxBaseConnector] - Listener removed: org.openhab.binding.vallox.internal.se.handler.ValloxSEHandler@b3d61a

2020-04-28 13:47:49.120 [DEBUG] [.se.connection.ValloxSerialConnector] - Serial connection closed

2020-04-28 13:47:49.119 [DEBUG] [al.se.connection.ValloxBaseConnector] - Listener removed: org.openhab.binding.vallox.internal.se.handler.ValloxSEHandler@394fc

2020-04-28 13:47:49.125 [DEBUG] [.se.connection.ValloxSerialConnector] - Serial connection closed

2020-04-28 13:47:49.126 [DEBUG] [al.se.connection.ValloxBaseConnector] - Listener registered: org.openhab.binding.vallox.internal.se.handler.ValloxSEHandler@b3d61a

2020-04-28 13:47:49.127 [DEBUG] [al.se.connection.ValloxBaseConnector] - Listener registered: org.openhab.binding.vallox.internal.se.handler.ValloxSEHandler@394fc

2020-04-28 13:47:49.127 [DEBUG] [.se.connection.ValloxSerialConnector] - Connecting to /dev/ttyUSB1

2020-04-28 13:47:49.131 [DEBUG] [.se.connection.ValloxSerialConnector] - Connecting to /dev/ttyUSB0

2020-04-28 13:47:52.131 [DEBUG] [.internal.se.handler.ValloxSEHandler] - Connection failed 

java.io.IOException: Port in use

	at org.openhab.binding.vallox.internal.se.connection.ValloxSerialConnector.connect(ValloxSerialConnector.java:90) ~[?:?]

	at org.openhab.binding.vallox.internal.se.handler.ValloxSEHandler.connect(ValloxSEHandler.java:102) ~[?:?]

	at org.openhab.binding.vallox.internal.se.handler.ValloxSEHandler.checkConnection(ValloxSEHandler.java:378) ~[?:?]

	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_222]

	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_222]

	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_222]

	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_222]

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_222]

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_222]

	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]

Caused by: org.eclipse.smarthome.io.transport.serial.PortInUseException

	at org.eclipse.smarthome.io.transport.serial.internal.SerialPortIdentifierImpl.open(SerialPortIdentifierImpl.java:61) ~[?:?]

	at org.openhab.binding.vallox.internal.se.connection.ValloxSerialConnector.connect(ValloxSerialConnector.java:65) ~[?:?]

	... 9 more

2020-04-28 13:47:52.134 [DEBUG] [.internal.se.handler.ValloxSEHandler] - Connection failed 

java.io.IOException: Port in use

	at org.openhab.binding.vallox.internal.se.connection.ValloxSerialConnector.connect(ValloxSerialConnector.java:90) ~[?:?]

	at org.openhab.binding.vallox.internal.se.handler.ValloxSEHandler.connect(ValloxSEHandler.java:102) ~[?:?]

	at org.openhab.binding.vallox.internal.se.handler.ValloxSEHandler.checkConnection(ValloxSEHandler.java:378) ~[?:?]

	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_222]

	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_222]

	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_222]

	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_222]

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_222]

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_222]

	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]

Caused by: org.eclipse.smarthome.io.transport.serial.PortInUseException

	at org.eclipse.smarthome.io.transport.serial.internal.SerialPortIdentifierImpl.open(SerialPortIdentifierImpl.java:61) ~[?:?]

	at org.openhab.binding.vallox.internal.se.connection.ValloxSerialConnector.connect(ValloxSerialConnector.java:65) ~[?:?]

	... 9 more
```

**Comment by gitMiguel** [comment]
Hmm, can you tell me when does this usually happen? At random intervals at startup maybe? Or does the connection drop during normal usage and the binding restarts?

**Comment by Sprocket02** [comment]
Sporadically with the official version. But with the latest beta that you have [provided](https://community.openhab.org/t/new-vallox-binding/86425/16?u=sebastian_neu) for me with every change of the fan speed.

**Comment by gitMiguel** [comment]
Seems weird. Can you send me longer part of your log? I need to see everything from beginning.

**Comment by gitMiguel** [comment]
I've set up serial dev environment for my self to better understand whats wrong. No need for the log anymore.
